version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.2
    - 11.1.3
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: trezor-connect
    versions:
    - 8.1.20
    - 8.1.21
    - 8.1.22
    - 8.1.23
    - 8.1.24
    - 8.1.25
  - dependency-name: rxjs
    versions:
    - 6.6.3
    - 6.6.6
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.901.13
    - 0.901.14
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
