export const accountData = [
  {
    'code': 'XDR',
    'name': 'Pays XDR',
    'icon': '/assets/img/xdr-coin.svg',
    'balance': '0',
    'percent': '30',
    'value': 0,
    'change': '+5',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
  },
  {
    'code': 'XLM',
    'name': 'Lumen',
    'icon': '/assets/img/XLM.png',
    'balance': '0',
    'percent': '33',
    'value': 0,
    'change': 0,
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
  },
  {
    'code': 'BTC',
    'name': 'Bitcoin',
    'icon': 'https://apay.io/public/logo/btc.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
  },
  {
    'code': 'BCH',
    'name': 'Bitcoin Cash',
    'icon': 'https://apay.io/public/logo/bch.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
  },
  {
    'code': 'ETH',
    'name': 'Ethereum',
    'icon': 'https://apay.io/public/logo/eth.png',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
  },
  {
    'code': 'LTC',
    'name': 'Litecoin',
    'icon': 'https://apay.io/public/logo/ltc.png',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
  },
  {
    'code': 'BAT',
    'name': 'Basic Attention Token',
    'icon': 'https://apay.io/public/logo/bat.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
  },
  {
    'code': 'KIN',
    'name': 'Kin',
    'icon': 'https://apay.io/public/logo/kin.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
  },
  {
    'code': 'LINK',
    'name': 'ChainLink',
    'icon': 'https://apay.io/public/logo/link.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
  },
  {
    'code': 'MTL',
    'name': 'Metal',
    'icon': 'https://apay.io/public/logo/mtl.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
  },
  {
    'code': 'OMG',
    'name': 'OmiseGo',
    'icon': 'https://apay.io/public/logo/omg.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
  },
  {
    'code': 'REP',
    'name': 'Augur',
    'icon': 'https://apay.io/public/logo/rep.png',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
  },
  {
    'code': 'SALT',
    'name': 'SALT',
    'icon': 'https://apay.io/public/logo/salt.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
  },
  {
    'code': 'ZRX',
    'name': '0xProject',
    'icon': 'https://apay.io/public/logo/zrx.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
  }
];
