export const accountData = [
  {
    'code': 'XDR',
    'name': 'Pays XDR',
    'baseUrl': 'https://api.apay.io/api',
    'icon': '/assets/img/xdr-coin.svg',
    'balance': '0',
    'percent': '30',
    'value': 0,
    'change': '+5',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
    'deposit': 'active',
    'withdraw': 'active',
    'color': '#211265',
    'address': 'native',
    'trustline': false
  },
  {
    'code': 'XLM',
    'name': 'Lumen',
    'baseUrl': 'https://api.apay.io/api',
    'icon': '/assets/img/XLM.png',
    'balance': '0',
    'percent': '33',
    'value': 0,
    'change': 0,
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
    'deposit': 'active',
    'withdraw': 'active',
    'color': '#000000',
    'address': 'native',
    'trustline': false
  },
  {
    'code': 'BTC',
    'name': 'Bitcoin',
    'baseUrl': 'https://api.apay.io/api',
    'icon': 'https://apay.io/public/logo/btc.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
    'deposit': 'active',
    'withdraw': 'active',
    'color': '#f8a036',
    'address': 'non-native',
    'trustline': false
  },
  {
    'code': 'BCH',
    'name': 'Bitcoin Cash',
    'baseUrl': 'https://api.apay.io/api',
    'icon': 'https://apay.io/public/logo/bch.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
    'deposit': 'active',
    'withdraw': 'active',
    'color': '#548d1d',
    'address': 'non-native',
    'trustline': false
  },
  {
    'code': 'ETH',
    'name': 'Ethereum',
    'baseUrl': 'https://api.apay.io/api',
    'icon': 'https://apay.io/public/logo/eth.png',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
    'deposit': 'active',
    'withdraw': 'active',
    'color': '#9c68aa',
    'address': 'non-native',
    'trustline': false
  },
  {
    'code': 'LTC',
    'name': 'Litecoin',
    'baseUrl': 'https://api.apay.io/api',
    'icon': 'https://apay.io/public/logo/ltc.png',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
    'deposit': 'active',
    'withdraw': 'active',
    'color': '#315d9e',
    'address': 'non-native',
    'trustline': false
  },
  {
    'code': 'BAT',
    'name': 'Basic Attention Token',
    'baseUrl': 'https://api.apay.io/api',
    'icon': 'https://apay.io/public/logo/bat.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
    'deposit': 'active',
    'withdraw': 'active',
    'color': '#ff5000',
    'address': 'non-native',
    'trustline': false
  },
  {
    'code': 'KIN',
    'name': 'Kin',
    'baseUrl': 'https://api.apay.io/api',
    'icon': 'https://apay.io/public/logo/kin.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
    'deposit': 'active',
    'withdraw': 'active',
    'color': '#005fff',
    'address': 'non-native',
    'trustline': false
  },
  {
    'code': 'LINK',
    'name': 'ChainLink',
    'baseUrl': 'https://api.apay.io/api',
    'icon': 'https://apay.io/public/logo/link.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
    'deposit': 'active',
    'withdraw': 'active',
    'color': '#3fa0f1',
    'address': 'non-native',
    'trustline': false
  },
  {
    'code': 'MTL',
    'name': 'Metal',
    'baseUrl': 'https://api.apay.io/api',
    'icon': 'https://apay.io/public/logo/mtl.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
    'deposit': 'active',
    'withdraw': 'active',
    'color': '#1e1f25',
    'address': 'non-native',
    'trustline': false
  },
  {
    'code': 'OMG',
    'name': 'OmiseGo',
    'baseUrl': 'https://api.apay.io/api',
    'icon': 'https://apay.io/public/logo/omg.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
    'deposit': 'active',
    'withdraw': 'active',
    'color': '#1a53f0',
    'address': 'non-native',
    'trustline': false
  },
  {
    'code': 'REP',
    'name': 'Augur',
    'baseUrl': 'https://api.apay.io/api',
    'icon': 'https://apay.io/public/logo/rep.png',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
    'deposit': 'active',
    'withdraw': 'active',
    'color': '#ae9fc1',
    'address': 'non-native',
    'trustline': false
  },
  {
    'code': 'SALT',
    'name': 'SALT',
    'baseUrl': 'https://api.apay.io/api',
    'icon': 'https://apay.io/public/logo/salt.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
    'deposit': 'active',
    'withdraw': 'active',
    'color': '#369da3',
    'address': 'non-native',
    'trustline': false
  },
  {
    'code': 'ZRX',
    'name': '0xProject',
    'baseUrl': 'https://api.apay.io/api',
    'icon': 'https://apay.io/public/logo/zrx.svg',
    'balance': '0',
    'percent': '37',
    'value': 0,
    'change': '-2',
    'chart': [0, 1, 2, 1, 0, 4, 7, 3, 1, 2, 1, 0, 4, 7, 3],
    'deposit': 'active',
    'withdraw': 'active',
    'color': '#000',
    'address': 'non-native',
    'trustline': false
  }
];
