export const markets = [
  {
    'account': 'GAPAYCA6MWFTEMXM4FK2W6WSWBJNIN2ZX7GXIILR7H3PHUVXCWZCYBTC',
    'manager': 'GCFJL4C74ET4OHOYNUXXVLBZISITRYVHRVKIU7NE7KY52EJKNOUWIC25',
    'base': { 'asset_type': 'credit_alphanum4', 'asset_code': 'USDT', 'asset_issuer': 'GCQTGZQQ5G4PTM2GL7CDIFKUBIPEC52BROAQIAPW53XBRJVN6ZJVTG6V' },
    'asset': { 'asset_type': 'credit_alphanum4', 'asset_code': 'BTC', 'asset_issuer': 'GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF' },
    unit: 'APAYBTC'
  },
  {
    'account': 'GAPAYXB5SWYZYOF2TQ5U7LYOSL4AL6XMJFHQWVLQ2IY5ZR43H6H5XETH',
    'manager': 'GCSFNCXDRP45OUMK2Y36L6WQLBTWKJYNJZJVYVGV77KXSTDYUKRL2KHM',
    'base': { 'asset_type': 'credit_alphanum4', 'asset_code': 'USDT', 'asset_issuer': 'GCQTGZQQ5G4PTM2GL7CDIFKUBIPEC52BROAQIAPW53XBRJVN6ZJVTG6V' },
    'asset': { 'asset_type': 'credit_alphanum4', 'asset_code': 'ETH', 'asset_issuer': 'GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR' },
    unit: 'APAYETH'
  },
  {
    'account': 'GAPAYL74TUE56E4IAOAT6YCGEDS4MBG24UILXKFH3FN3D4OGZC6FILTC',
    'manager': 'GB24ZB3P7NSRCUNAYOSILEM45C7HCG2RFAJGTAXP6L4C7TB75QYYW2AS',
    'base': { 'asset_type': 'credit_alphanum4', 'asset_code': 'USDT', 'asset_issuer': 'GCQTGZQQ5G4PTM2GL7CDIFKUBIPEC52BROAQIAPW53XBRJVN6ZJVTG6V' },
    'asset': { 'asset_type': 'credit_alphanum4', 'asset_code': 'LTC', 'asset_issuer': 'GC5LOR3BK6KIOK7GKAUD5EGHQCMFOGHJTC7I3ELB66PTDFXORC2VM5LP' },
    unit: 'APAYLTC'
  },
  {
    'account': 'GAPAY4IE6ANI5YWSCSUFIH55UVIF7REC2QHVEOZD23YNJILTVVSUJKIN',
    'manager': 'GAG6FM2UROXHM4SZEQI2KIZLP65MPPGFUCPWGQU3UI5GG27MHDCZSOJS',
    'base': { 'asset_type': 'credit_alphanum4', 'asset_code': 'USDT', 'asset_issuer': 'GCQTGZQQ5G4PTM2GL7CDIFKUBIPEC52BROAQIAPW53XBRJVN6ZJVTG6V' },
    'asset': { 'asset_type': 'credit_alphanum4', 'asset_code': 'KIN', 'asset_issuer': 'GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR' },
    unit: 'APAYKIN'
  },
  {
    'account': 'GAPAY67M7FIOV4C3K6MYASRKEGQ7L6A6ME5GDLNAI4FYMOOJRI574REP',
    'manager': 'GA72SULA2XFRPGWMLKCTHAFVYE5IF6ARSTP3W24UXBZN2Y2QMJXUN4BN',
    'base': { 'asset_type': 'credit_alphanum4', 'asset_code': 'USDT', 'asset_issuer': 'GCQTGZQQ5G4PTM2GL7CDIFKUBIPEC52BROAQIAPW53XBRJVN6ZJVTG6V' },
    'asset': { 'asset_type': 'credit_alphanum4', 'asset_code': 'REP', 'asset_issuer': 'GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR' },
    unit: 'APAYREP'
  },
  {
    'account': 'GAPAYOQIGNEUJ6NA4PLKHGAHJ54YMKAUWV7UG5KWKARHV5N5C3FLQXLM',
    'manager': 'GA2JCLA2IOPWZ6PMCSFVS3UP26DOXD65L4XKG43LQ6K3DFPTB4ZBPYZT',
    'base': { 'asset_type': 'credit_alphanum4', 'asset_code': 'USDT', 'asset_issuer': 'GCQTGZQQ5G4PTM2GL7CDIFKUBIPEC52BROAQIAPW53XBRJVN6ZJVTG6V' },
    'asset': { 'asset_type': 'native' },
    unit: 'APAYXLM'
  },
  {
    'account': 'GAPAYLAWTLHGYP2226HDUY4CSZFZYA5WIB3RPCOSFUO44RDIOE5IBBAT',
    'manager': 'GCJHEJ7OKYQ4FXWT6RCL3V3NALUJO5N4HFXH3R2GXPYWHVEIF6LH5LG5',
    'base': { 'asset_type': 'credit_alphanum4', 'asset_code': 'USDT', 'asset_issuer': 'GCQTGZQQ5G4PTM2GL7CDIFKUBIPEC52BROAQIAPW53XBRJVN6ZJVTG6V' },
    'asset': { 'asset_type': 'credit_alphanum4', 'asset_code': 'BAT', 'asset_issuer': 'GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR' },
    unit: 'APAYBAT'
  },
  {
    'account': 'GAPAYYMTERZK7RX27IFI62DQSKGK5SNOYRIPJ3UCIB3DVK7TDN32LINK',
    'manager': 'GBQLVYGZF7UVYEVWEIH6LUCOAW4D7QY24WJ5GZZZNNH5FV6K33BHBCCB',
    'base': { 'asset_type': 'credit_alphanum4', 'asset_code': 'USDT', 'asset_issuer': 'GCQTGZQQ5G4PTM2GL7CDIFKUBIPEC52BROAQIAPW53XBRJVN6ZJVTG6V' },
    'asset': { 'asset_type': 'credit_alphanum4', 'asset_code': 'LINK', 'asset_issuer': 'GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR' },
    unit: 'APAYLINK'
  },
  {
    'account': 'GAPAYLR747AI2TE25ZC56YFXTJP5C63F5JDBZMUJP235X23M635UUOMG',
    'manager': 'GAWLY4XATIWRKSDQUVACSDDBSWF4JNPQZXQZEREZRJU75SGI72PZG72O',
    'base': { 'asset_type': 'credit_alphanum4', 'asset_code': 'USDT', 'asset_issuer': 'GCQTGZQQ5G4PTM2GL7CDIFKUBIPEC52BROAQIAPW53XBRJVN6ZJVTG6V' },
    'asset': { 'asset_type': 'credit_alphanum4', 'asset_code': 'OMG', 'asset_issuer': 'GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR' },
    unit: 'APAYOMG'
  },
  {
    'account': 'GAPAY2422NNVPAEWJLZS6XXB3QS2ODTWKYUW2U2YJ6OK73QMGA6UUZRX',
    'manager': 'GAFYJBB7N5MB4RSMRUA7LXBXEETXHTYNBBI3GFSEZR2V2ERO2BDFMX7R',
    'base': { 'asset_type': 'credit_alphanum4', 'asset_code': 'USDT', 'asset_issuer': 'GCQTGZQQ5G4PTM2GL7CDIFKUBIPEC52BROAQIAPW53XBRJVN6ZJVTG6V' },
    'asset': { 'asset_type': 'credit_alphanum4', 'asset_code': 'ZRX', 'asset_issuer': 'GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR' },
    unit: 'APAYZRX'
  },
];
